Import('proto_files_go')

env = Environment(
    ENV={
        "CGO_ENABLED": "0",
        "GOPATH": "/root/go"
    })


env.Command(
    ['controller'],
    [
        'debugger.go',
        'ec2_provider.go',
        'local_provider.go',
        'main.go',
    ],
    '/usr/local/go/bin/go build -o $TARGET -a -installsuffix cgo $SOURCES')

env.Depends("controller", proto_files_go)
