Import('proto_files_go')

env = Environment(
    ENV={
        "CGO_ENABLED": "0",
        "GOPATH": "/root/go"
    })


env.Command(
    ['controller'],
    ['main.go', 'provider.go', 'debugger.go'],
    '/usr/local/go/bin/go build -o $TARGET -a -installsuffix cgo $SOURCES')

env.Depends("controller", proto_files_go)
